version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - ../.env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - ../.env
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception_network
    restart: on-failure
    env_file:
      - ../.env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
  inception_network:
    driver: bridge
